"""Write src/lib/locales/*.ts from scripts/locales/strings.py.

Usage: python3 scripts/make-locales.py
Fails if a row is short, repeats a key, or loses a {placeholder}.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "locales"))
from strings import LANGS, ROWS  # noqa: E402

OUT = os.path.join(HERE, "..", "src", "lib", "locales")
PLACEHOLDER = re.compile(r"\{\w+\}")


def check(key, lang, value):
    forms = value.values() if isinstance(value, dict) else [value]
    wanted = set(PLACEHOLDER.findall(key))
    for form in forms:
        extra = set(PLACEHOLDER.findall(form)) - wanted
        assert not extra, (lang, key, extra)
    if not isinstance(value, dict):
        missing = wanted - set(PLACEHOLDER.findall(value))
        assert not missing, (lang, key, missing)
    else:
        assert "other" in value, (lang, key)


def main():
    keys = [row[0] for row in ROWS]
    assert len(keys) == len(set(keys)), [k for k in keys if keys.count(k) > 1]
    os.makedirs(OUT, exist_ok=True)
    for index, lang in enumerate(LANGS, start=1):
        lines = [
            "// Generated by scripts/make-locales.py from scripts/locales/strings.py.",
            "// Edit the translations there, not here.",
            'import type { Table } from "../i18n";',
            "",
            "export const %s: Table = {" % lang,
        ]
        for row in ROWS:
            assert len(row) == len(LANGS) + 1, row[0]
            value = row[index]
            check(row[0], lang, value)
            key = json.dumps(row[0], ensure_ascii=False)
            if isinstance(value, dict):
                lines.append("\t%s: {" % key)
                for category, form in value.items():
                    lines.append(
                        "\t\t%s: %s," % (category, json.dumps(form, ensure_ascii=False))
                    )
                lines.append("\t},")
            else:
                lines.append("\t%s: %s," % (key, json.dumps(value, ensure_ascii=False)))
        lines.append("};")
        path = os.path.join(OUT, "%s.ts" % lang)
        io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("wrote %d strings in %s" % (len(ROWS), ", ".join(LANGS)))


if __name__ == "__main__":
    main()
